version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - migueldemoura
    assignees:
      - migueldemoura
